spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.7:3306/spring_cache?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    initialization-mode: always
  redis:
    host: 192.168.0.7
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.yonyou.mapper: debug
debug: true



